-- Prva migracia: tabulka uloh.
-- Zodpoveda entite org.example.example.entity.Task.
-- Uz vykonanu migraciu sa NIKDY neupravuje - kazda dalsia zmena schemy ide do noveho suboru V2__..., V3__...
CREATE TABLE tasks (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title     VARCHAR(255) NOT NULL,
    completed BOOLEAN      NOT NULL,
    due_at    TIMESTAMP(6)
);
